### ISSUE TITLE
suggestions

### ISSUE THREAD

**Issue by ShiSix** [faldez/shachi#1]
add sankaku complex
add option for seleting default from save ,browse,fav 
add option for save tags 
add some tags in search like order:score etc

**Comment by faldez** [comment]
> add sankaku complex
I want to focus on booru service for a while

> add option for seleting default from save ,browse,fav
what do you mean by this?

> add option for save tags
you already can save tags as saved search, is it what you want?

> add some tags in search like order:score etc
you can type this manually, do you want some kind of button?

**Comment by ShiSix** [comment]
when i open app first tab opens that is "saved"  but i like to browse be default

**Comment by ShiSix** [comment]
![Uploading Screenshot_20220402-192633_Flexbooru.png…]()

**Comment by ShiSix** [comment]
![Screenshot_20220402-192633_Flexbooru](https://user-images.githubusercontent.com/101547113/161386684-59af159a-1a95-44f3-8271-4eeccf0a5ea8.png)

**Comment by ShiSix** [comment]
saved tag when seaching
